// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmaM.Data;

#nullable disable

namespace PharmaM.Infrastructure.Migrations
{
    [DbContext(typeof(PharmaMDbContext))]
    partial class PharmaMDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "f9edb0de-fda1-47b6-8932-d3cf64a7eabb",
                            ConcurrencyStamp = "59c79a4d-a182-4aa8-a0c7-9811c3016d13",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "aec9bf40-5990-4fe7-bac3-a543da631b54",
                            ConcurrencyStamp = "f434c168-2704-4afc-9345-7497e86de8a9",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "180c0957-5eb9-4c4a-b0c5-90a3c609b981",
                            RoleId = "aec9bf40-5990-4fe7-bac3-a543da631b54"
                        },
                        new
                        {
                            UserId = "70ad7c70-d2e2-41b0-80dc-d76e2622113b",
                            RoleId = "f9edb0de-fda1-47b6-8932-d3cf64a7eabb"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PharmaM.Infrastructure.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Address User for delivery");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("First Name User");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Last Name User");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Phone Number User");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasComment("Application User");

                    b.HasData(
                        new
                        {
                            Id = "180c0957-5eb9-4c4a-b0c5-90a3c609b981",
                            AccessFailedCount = 0,
                            Address = "",
                            ConcurrencyStamp = "ed276da3-8689-4410-a4eb-17c19973fcb1",
                            Email = "user2@hotmail.com",
                            EmailConfirmed = false,
                            FirstName = "",
                            LastName = "",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER2@HOTMAIL.COM",
                            NormalizedUserName = "USER2@HOTMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEOInAAsgyEk+50juWfbBscjCfyBa1kRSllBB9/IMC8ql06A71JImYlPyEsBufBHPTQ==",
                            Phone = "",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e8ffd692-6d06-4726-a5bd-ed7daf67a2df",
                            TwoFactorEnabled = false,
                            UserName = "user2@hotmail.com"
                        },
                        new
                        {
                            Id = "70ad7c70-d2e2-41b0-80dc-d76e2622113b",
                            AccessFailedCount = 0,
                            Address = "",
                            ConcurrencyStamp = "05411263-7cf7-4633-bba6-3d823b5936c7",
                            Email = "user3@hotmail.com",
                            EmailConfirmed = false,
                            FirstName = "",
                            LastName = "",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER3@HOTMAIL.COM",
                            NormalizedUserName = "USER3@HOTMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEI8sdu9ABNTwGIGghxqbCJfk5B00/BFytLoT8qont4dPefAhDTq1wKsQ5SZkmUyOZg==",
                            Phone = "",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ea14b934-13bd-4963-98d3-f4eef3912eb8",
                            TwoFactorEnabled = false,
                            UserName = "user3@hotmail.com"
                        });
                });

            modelBuilder.Entity("PharmaM.Infrastructure.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasComment("Category Name");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasComment("Product Name");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasComment("Category Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Medicines",
                            ProductId = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Food supplements",
                            ProductId = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Homeopathy",
                            ProductId = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Diet",
                            ProductId = 0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cosmetics",
                            ProductId = 0
                        },
                        new
                        {
                            Id = 6,
                            Name = "Appliances",
                            ProductId = 0
                        });
                });

            modelBuilder.Entity("PharmaM.Infrastructure.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Order Identifire");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("StatusOrder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeOrdered")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasComment("User Order");
                });

            modelBuilder.Entity("PharmaM.Infrastructure.Data.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasComment("Order Identifire");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasComment("Product Identifire");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasComment("OrderItem Identifire");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price order");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("Quantity of order");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasComment("Order item");
                });

            modelBuilder.Entity("PharmaM.Infrastructure.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasComment("Category ID of the product");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Description of the product");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image URL of the product");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Name of the product");

                    b.Property<bool>("NeedsPrescription")
                        .HasColumnType("bit")
                        .HasComment("Needs of Prescription for the product");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price the product");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("Products");

                    b.HasComment("Product for the PharmaM");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 5,
                            Description = "Sensibio H2O AR is the 1st make-up removing micellar water that mimics the skin's natural composition for perfect make-up removal and total respect for even the most sensitive skin. It also inhibits redness, by biologically regulating the factor responsible for vasodilation. ",
                            ImageURL = "~/images/product_01.png",
                            Name = "Bioderma",
                            NeedsPrescription = false,
                            Price = 7m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Experience the phytonutrient power of Swanson Full Spectrum® Chanca Piedra. Chanca piedra has been in use throughout South America, India and China for centuries. Although different species grow and are used in different regions of the world, only Phyllanthus niruri is known to contain the active phytonutrients believed to be responsible for the herb's unique benefits. This herb was used historically to support kidney health, liver health and more!",
                            ImageURL = "~/images/product_02.png",
                            Name = "Chanca Pedra",
                            NeedsPrescription = true,
                            Price = 11m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Sip on Comforting Care.When you’re feeling sick, enjoying a warm beverage can be a comforting ritual. This homeopathic remedy is clinically proven to shorten the duration and reduce the severity of congestion, cough, sore throat, and nasal and bronchial irritation while providing a soothing, relaxing experience. May also be served cold. For ages 6+.",
                            ImageURL = "~/images/product_03.png",
                            Name = "Umcka ColdCare",
                            NeedsPrescription = false,
                            Price = 5m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Umcka ColdCare Alcohol-Free Drops are clinically proven to shorten the duration and reduce the severity of cough, congestion, sore throat, and nasal and bronchial irritations. The included dropper provides convenient dosage. Take them straight or add drops to a beverage like tea or water to start feeling better, faster. ",
                            ImageURL = "~/images/product_03.png",
                            Name = "Umcka® ColdCare Alcohol-Free Drops",
                            NeedsPrescription = false,
                            Price = 15m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "As our bodies age, the ability to produce some of the nutrients necessary for joint function and cartilage building declines. CetylPure from “Natrol” helps to nourish and maintain the lubricating fluid in joints and cartilage, which is enough to give you optimal joint health and relief from any joint pain you suffer from, especially after workout sessions.",
                            ImageURL = "~/images/product_04.png",
                            Name = "Cetyl Pure",
                            NeedsPrescription = true,
                            Price = 25m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            Description = "CLA Core Blend - a combination of conjugated linoleic acid, exclusively pure zetin and a small amount of avocado. cla core conjugated linoleic acid has a synergistic effect - the substances increase their effectiveness when used together.",
                            ImageURL = "~/images/product_05.png",
                            Name = "CLACore",
                            NeedsPrescription = false,
                            Price = 8m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "oo-Pourri Before-You-Go Toilet Spray leaves your bathroom smelling fresh and clean. Simply spray the water in the bowl with Poo-Pourri Toilet Spray before using the toilet to prevent odors before they begin! ",
                            ImageURL = "~/images/product_06.png",
                            Name = "Poo-Pourt",
                            NeedsPrescription = true,
                            Price = 20m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Ibuprofen Polfa 200 mg coated tablets is a medicine for the symptomatic treatment of elevated body temperature and pain. It has a beneficial effect on complaints of muscle and menstrual pain, migraine and toothache. The active ingredient of Polpharma Ibuprofen Polfa is ibuprofen, which is a non-steroidal anti-inflammatory drug that is absorbed in the gastrointestinal tract.",
                            ImageURL = "~/images/product_07.png",
                            Name = "Ibuprofen",
                            NeedsPrescription = false,
                            Price = 8m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Nurofen StopCold combines the pain-relieving action of ibuprofen with the vasoconstrictor action of pseudoephedrine, relieving pain and symptoms of cold and flu, high fever, sore throat, congestion and runny nose for up to 8 hours.",
                            ImageURL = "~/images/product_07.png",
                            Name = "Nurofen Stop Cold",
                            NeedsPrescription = false,
                            Price = 8m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 6,
                            Description = "The Accu-Chek Instant system simplifies testing so patients can understand their results at a glance and have confidence in their daily lives.",
                            ImageURL = "~/images/product_07.png",
                            Name = "Accu Chek Instant glucometer kit + 50 test strips",
                            NeedsPrescription = false,
                            Price = 8m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            Description = "Bioname Glucometer GM 100 measures blood sugar quickly and easily. Controls diabetes at home. The meter is accurate and reliable, liked by professionals. The set includes a glucometer and 50 test strips.",
                            ImageURL = "~/images/product_07.png",
                            Name = "Bionime GM100",
                            NeedsPrescription = false,
                            Price = 8m
                        });
                });

            modelBuilder.Entity("PharmaM.Infrastructure.Data.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("PharmaM.Infrastructure.Data.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Item for buy identyfire");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasComment("Product Id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("Quantity item");

                    b.Property<int>("ShoppingCartId")
                        .HasColumnType("int")
                        .HasComment("ShoppingCart identyfire");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("ShoppingCartItems");

                    b.HasComment("Shopping Cart Item");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PharmaM.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PharmaM.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaM.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PharmaM.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaM.Infrastructure.Data.Models.Order", b =>
                {
                    b.HasOne("PharmaM.Infrastructure.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("PharmaM.Infrastructure.Data.Models.OrderItem", b =>
                {
                    b.HasOne("PharmaM.Infrastructure.Data.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaM.Infrastructure.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PharmaM.Infrastructure.Data.Models.Product", b =>
                {
                    b.HasOne("PharmaM.Infrastructure.Data.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaM.Infrastructure.Data.Models.Category", null)
                        .WithMany("Products")
                        .HasForeignKey("ProductId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PharmaM.Infrastructure.Data.Models.ShoppingCart", b =>
                {
                    b.HasOne("PharmaM.Infrastructure.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("PharmaM.Infrastructure.Data.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("PharmaM.Infrastructure.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaM.Infrastructure.Data.Models.ShoppingCart", "ShoppingCart")
                        .WithMany("ShoppingCartItems")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("PharmaM.Infrastructure.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("PharmaM.Infrastructure.Data.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PharmaM.Infrastructure.Data.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("PharmaM.Infrastructure.Data.Models.ShoppingCart", b =>
                {
                    b.Navigation("ShoppingCartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
